name: Desplegar a producción
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar script de despliegue dota2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd htdocs/ltddota.sistemasudh.com
            git reset --hard HEAD
            git pull origin main
            node -v
            npm -v
            npm install
            npx astro build
            /home/ltddota/.nvm/versions/node/v22.16.0/bin/pm2 stop ltddotaapp
            /home/ltddota/.nvm/versions/node/v22.16.0/bin/pm2 start ltddotaapp
            /home/ltddota/.nvm/versions/node/v22.16.0/bin/pm2 save
            git log --oneline
